[workspace.package]
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "engine-bencher",
    "memtable-nursery",
    "parquet-bencher",
]
resolver = "2"

[workspace.dependencies]
arrow-array = "43"
arrow-row = "43"
arrow-schema = "43"
api = { git = "https://github.com/evenyag/greptimedb.git", rev = "92640b5d09f82efb69b614440202c725f780ee40" }
common-base = { git = "https://github.com/evenyag/greptimedb.git", rev = "92640b5d09f82efb69b614440202c725f780ee40" }
common-config = { git = "https://github.com/evenyag/greptimedb.git", rev = "92640b5d09f82efb69b614440202c725f780ee40" }
common-runtime = { git = "https://github.com/evenyag/greptimedb.git", rev = "92640b5d09f82efb69b614440202c725f780ee40" }
common-telemetry = { git = "https://github.com/evenyag/greptimedb.git", rev = "92640b5d09f82efb69b614440202c725f780ee40" }
datatypes = { git = "https://github.com/evenyag/greptimedb.git", rev = "92640b5d09f82efb69b614440202c725f780ee40" }
futures-util = "0.3"
humantime-serde = "1"
log-store = { git = "https://github.com/evenyag/greptimedb.git", rev = "92640b5d09f82efb69b614440202c725f780ee40" }
mito2 = { git = "https://github.com/evenyag/greptimedb.git", rev = "92640b5d09f82efb69b614440202c725f780ee40" }
object-store = { git = "https://github.com/evenyag/greptimedb.git", rev = "92640b5d09f82efb69b614440202c725f780ee40" }
parquet = "43"
serde = { version = "1", features = ["derive"] }
storage = { git = "https://github.com/evenyag/greptimedb.git", rev = "92640b5d09f82efb69b614440202c725f780ee40" }
store-api = { git = "https://github.com/evenyag/greptimedb.git", rev = "92640b5d09f82efb69b614440202c725f780ee40" }
tokio = { version = "1", features = ["rt-multi-thread"] }
toml = "0.7"
