[workspace.package]
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "engine-bencher",
    "memtable-nursery",
    "parquet-bencher",
]

[workspace.dependencies]
arrow-array = "40"
common-base = { git = "https://github.com/evenyag/greptimedb.git", rev = "a599a211d28f626b2745226837b3869488c8f839" }
common-runtime = { git = "https://github.com/evenyag/greptimedb.git", rev = "a599a211d28f626b2745226837b3869488c8f839" }
common-telemetry = { git = "https://github.com/evenyag/greptimedb.git", rev = "a599a211d28f626b2745226837b3869488c8f839" }
datatypes = { git = "https://github.com/evenyag/greptimedb.git", rev = "a599a211d28f626b2745226837b3869488c8f839" }
futures-util = "0.3"
humantime-serde = "1"
log-store = { git = "https://github.com/evenyag/greptimedb.git", rev = "a599a211d28f626b2745226837b3869488c8f839" }
object-store = { git = "https://github.com/evenyag/greptimedb.git", rev = "a599a211d28f626b2745226837b3869488c8f839" }
parquet = "40"
serde = { version = "1", features = ["derive"] }
storage = { git = "https://github.com/evenyag/greptimedb.git", rev = "a599a211d28f626b2745226837b3869488c8f839" }
store-api = { git = "https://github.com/evenyag/greptimedb.git", rev = "a599a211d28f626b2745226837b3869488c8f839" }
tokio = "1"
toml = "0.7"
