[workspace.package]
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "engine-bencher",
    "memtable-nursery",
    "parquet-bencher",
]

[workspace.dependencies]
futures-util = "0.3"
humantime-serde = "1"
arrow-array = "40"
parquet = "40"
serde = { version = "1", features = ["derive"] }
tokio = "1"
toml = "0.7"
