[workspace.package]
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "engine-bencher",
    "memtable-nursery",
    "parquet-bencher",
]
resolver = "2"

[workspace.dependencies]
arrow-array = "43"
arrow-row = "43"
arrow-schema = "43"
common-base = { git = "https://github.com/evenyag/greptimedb.git", rev = "cd9b621715689591b84d457c013ec1bed6e83873" }
common-runtime = { git = "https://github.com/evenyag/greptimedb.git", rev = "cd9b621715689591b84d457c013ec1bed6e83873" }
common-telemetry = { git = "https://github.com/evenyag/greptimedb.git", rev = "cd9b621715689591b84d457c013ec1bed6e83873" }
datatypes = { git = "https://github.com/evenyag/greptimedb.git", rev = "cd9b621715689591b84d457c013ec1bed6e83873" }
futures-util = "0.3"
humantime-serde = "1"
log-store = { git = "https://github.com/evenyag/greptimedb.git", rev = "cd9b621715689591b84d457c013ec1bed6e83873" }
object-store = { git = "https://github.com/evenyag/greptimedb.git", rev = "cd9b621715689591b84d457c013ec1bed6e83873" }
parquet = "43"
serde = { version = "1", features = ["derive"] }
storage = { git = "https://github.com/evenyag/greptimedb.git", rev = "cd9b621715689591b84d457c013ec1bed6e83873" }
store-api = { git = "https://github.com/evenyag/greptimedb.git", rev = "cd9b621715689591b84d457c013ec1bed6e83873" }
tokio = "1"
toml = "0.7"
