[package]
name = "store-benches"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humantime-serde = "1"
parquet = "32"
serde = "1"
toml = "0.7"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "bench"
harness = false
